name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: catthehacker-ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4

      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: https://github.com/actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Tests
        run: uv run pytest
